name: chat
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  flutter_displaymode: ^0.6.0
  provider: ^6.1.1
  cloud_firestore: ^4.8.0
  firebase_messaging: ^14.7.10
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.5
  image_picker: ^0.8.5
  firebase_storage: ^11.6.0
  get_it: ^7.2.0
  email_validator: ^2.1.17
  fullscreen_image_viewer: ^0.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/avatar.jpg

  fonts:
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-Regular.ttf

    - family: RobotoSlabMedium
      fonts:
        - asset: assets/fonts/RobotoSlab-Medium.ttf

    - family: RobotoSlabLight
      fonts:
        - asset: assets/fonts/RobotoSlab-Light.ttf

